set(_CATKIN_CURRENT_PACKAGE "scannerbot_gazebo")
set(scannerbot_gazebo_VERSION "0.0.0")
set(scannerbot_gazebo_MAINTAINER "franz <franz@todo.todo>")
set(scannerbot_gazebo_PACKAGE_FORMAT "1")
set(scannerbot_gazebo_BUILD_DEPENDS "roscpp")
set(scannerbot_gazebo_BUILD_EXPORT_DEPENDS "roscpp")
set(scannerbot_gazebo_BUILDTOOL_DEPENDS "catkin")
set(scannerbot_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(scannerbot_gazebo_EXEC_DEPENDS "roscpp")
set(scannerbot_gazebo_RUN_DEPENDS "roscpp")
set(scannerbot_gazebo_TEST_DEPENDS )
set(scannerbot_gazebo_DOC_DEPENDS )
set(scannerbot_gazebo_DEPRECATED "")